# Uncomment the next line to define a global platform for your project
platform :ios, '9.2'

target 'WAPI' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WAPI
  # Make sure we're also using React-Native from ../node_modules
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTWebSocket',
    'RCTGeolocation',
    'RCTLinkingIOS',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTImage',
    'RCTAnimation',
    'RCTActionSheet',
    'RCTCameraRoll',
    'RCTPushNotification',
  ]

  # React-Native dependencies such as yoga:
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # Now our RN libs
  pod 'RadarSDK', '~> 1.3.0'
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'RCTRestart', :path => '../node_modules/react-native-restart/ios'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'SentryReactNative', :path => '../node_modules/react-native-sentry/SentryReactNative.podspec'
  pod 'ReactNativeExceptionHandler', :path => '../node_modules/react-native-exception-handler/ios/ReactNativeExceptionHandler.podspec'

  target 'WAPITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'WAPI-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WAPI-tvOS

  target 'WAPI-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
