install! 'cocoapods',
         :deterministic_uuids => false,
         :integrate_targets => false

# Uncomment the next line to define a global platform for your project
platform :ios, '9.2'

target 'WAPI' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WAPI
  # Make sure we're also using React-Native from ../node_modules
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTWebSocket',
    'RCTGeolocation',
    'RCTLinkingIOS',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTImage',
    'RCTAnimation',
    'RCTActionSheet',
    'RCTCameraRoll',
    'RCTPushNotification',
  ]

  # React-Native dependencies such as yoga:
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # Now our RN libs
  pod 'RadarSDK', '~> 1.3.0'
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'RCTRestart', :path => '../node_modules/react-native-restart/ios'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'SentryReactNative', :path => '../node_modules/react-native-sentry/SentryReactNative.podspec'
  pod 'ReactNativeExceptionHandler', :podspec => '../node_modules/react-native-exception-handler/ios/ReactNativeExceptionHandler.podspec'
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

  target 'WAPITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'WAPI-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WAPI-tvOS

  target 'WAPI-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# WORKAROUND: https://github.com/facebook/react-native/issues/17274#issuecomment-356363557
post_install do |installer|
  installer.pods_project.targets.each do |target|
      if target.name == 'yoga'
          target.build_configurations.each do |config|
              config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
              config.build_settings['GCC_WARN_64_TO_32_BIT_CONVERSION'] = 'NO'
              config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
          end
      end

      if target.name == "React"
        target.remove_from_project
      end
  end
end
