# Uncomment the next line to define a global platform for your project
platform :ios, '11.2'

target 'WAPI' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WAPI
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
   'Core',
   'RCTText',
   'RCTImage',
   'RCTNetwork',
   'RCTSettings',
   'DevSupport',
   'RCTAnimation',
   'RCTWebSocket', # needed for localhost testing of your app
   'BatchedBridge',
   # Add any other subspecs you want to use in your project
  ]
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  
  pod 'RadarSDK', '~> 1.2.0'
  pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'

  target 'WAPITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'WAPI-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WAPI-tvOS

  target 'WAPI-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
