/* ------------- Auth Types ------------- */
export const AUTH_LOADING = 'AUTH_LOADING';
export const CLEAR_INPUT_DATA = 'CLEAR_INPUT_DATA';
export const AUTH_FIELD_CHANGED = 'AUTH_FIELD_CHANGED';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';
export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS';

/* ------------- App Types ------------- */
export const DONE_SURVEY = 'DONE_SURVEY';
export const DONE_APP_INTRO = 'DONE_APP_INTRO';
export const APP_FIELD_CHANGED = 'APP_FIELD_CHANGED';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const ADD_FAVOURITE = 'ADD_FAVOURITE';
export const REMOVE_FAVOURITE = 'REMOVE_FAVOURITE';

/* ------------- Listing Types ------------- */
export const CLEAR_LISTINGS = 'CLEAR_LISTINGS';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const SEARCH_FIELD_CHANGED = 'SEARCH_FIELD_CHANGED';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';
export const FETCH_LISTINGS_SUCCESS = 'FETCH_LISTINGS_SUCCESS';
export const FETCH_LISTINGS_FAILURE = 'FETCH_LISTINGS_FAILURE';
export const FETCH_LISTING_SUCCESS = 'FETCH_LISTING_SUCCESS';
export const FETCH_LISTING_FAILURE = 'FETCH_LISTING_FAILURE';
export const SEARCH_LISTINGS_SUCCESS = 'SEARCH_LISTINGS_SUCCESS';
export const SEARCH_LISTINGS_FAILURE = 'SEARCH_LISTINGS_FAILURE';
